<?php require_once 'includes/bootstrap.php';
$pdo=db(); $courseCount=(int)$pdo->query("SELECT COUNT(*) FROM courses WHERE is_active=1")->fetchColumn(); $userCount=(int)$pdo->query("SELECT COUNT(*) FROM users")->fetchColumn();
page_head('Home','Learn with Nazmul is a dynamic learning management platform providing accessible online courses, organised resources and practical digital learning.'); site_header('index.php'); render_flash();
echo '<script type="application/ld+json">'.json_encode(["@context"=>"https://schema.org","@type"=>"EducationalOrganization","name"=>"Learn with Nazmul","description"=>"Dynamic learning management platform for accessible digital education"]).'</script>'; 
$featured=$pdo->query("SELECT id,title,short_description,level,image FROM courses WHERE is_active=1 ORDER BY id LIMIT 3")->fetchAll(); ?>
<main>
<section class="hero" aria-labelledby="hero-title"><div class="hero-content"><p class="eyebrow">LEARNING MANAGEMENT SYSTEM</p><h1 id="hero-title">Learn Smarter.<br>Grow Further.</h1><p class="hero-description">Learn with Nazmul is a dynamic learning management platform designed to provide students with accessible courses, organised learning resources and flexible digital education opportunities for developing knowledge and practical skills.</p><div class="hero-buttons"><a class="button primary-button" href="<?= e(url('courses.php')) ?>">Explore Courses</a><a class="button secondary-button" href="<?= e(url('about.php')) ?>">Learn About Us</a></div></div><figure class="hero-image"><img src="<?= e(url('images/hero-learning.jpg')) ?>" alt="Student using a laptop to participate in online learning"><figcaption>Flexible digital learning from anywhere.</figcaption></figure></section>
<section class="stats-section" aria-label="Platform statistics"><div class="stats-grid"><div class="stat-card"><strong><?= $courseCount ?></strong><span>Active courses</span></div><div class="stat-card"><strong><?= $userCount ?></strong><span>Registered learners</span></div><div class="stat-card"><strong>24/7</strong><span>Online access</span></div></div></section>
<section aria-labelledby="features-title"><div class="section-heading"><p class="section-label">WHY LEARN WITH US?</p><h2 id="features-title">A Simple Approach to Digital Learning</h2><p>Important learning resources are brought together in one clear and accessible environment.</p></div><div class="features-grid"><article class="feature-card"><div class="feature-icon" aria-hidden="true">🎓</div><h3>Student Focused</h3><p>Clear course information and organised learning content support different learning goals.</p></article><article class="feature-card"><div class="feature-icon" aria-hidden="true">💻</div><h3>Flexible Access</h3><p>Access the platform online using desktop, tablet or mobile devices.</p></article><article class="feature-card"><div class="feature-icon" aria-hidden="true">🔒</div><h3>Secure Accounts</h3><p>Passwords are hashed and authenticated sessions protect member areas.</p></article></div></section>
<section class="alt-section" aria-labelledby="featured-title"><div class="section-heading"><p class="section-label">START LEARNING</p><h2 id="featured-title">Featured Courses</h2><p>Choose a topic and enrol after creating an account.</p></div><div class="course-grid"><?php foreach($featured as $c): ?><article class="course-card"><img src="<?= e(url('images/'.$c['image'])) ?>" alt="Course image for <?= e($c['title']) ?>"><div class="course-card-body"><span class="badge"><?= e($c['level']) ?></span><h3><?= e($c['title']) ?></h3><p><?= e($c['short_description']) ?></p><a href="<?= e(url('course.php?id='.$c['id'])) ?>">View course <span aria-hidden="true">→</span></a></div></article><?php endforeach; ?></div></section>
<section class="cta-section"><div><p class="section-label">READY TO START?</p><h2>Create your learning account</h2><p>Register for free, explore courses and keep track of your enrolments from your dashboard.</p><a class="button primary-button" href="<?= e(url('register.php')) ?>">Create an account</a></div></section>
</main><?php site_footer(); ?>